[2022-03-17 19:01:28,838] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: udac_example_dag.task_loadDataFromS3ToTrips.Stage_staging_songs scheduled__2022-03-17T10:00:00+00:00 [queued]>
[2022-03-17 19:01:28,848] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: udac_example_dag.task_loadDataFromS3ToTrips.Stage_staging_songs scheduled__2022-03-17T10:00:00+00:00 [queued]>
[2022-03-17 19:01:28,848] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-17 19:01:28,848] {taskinstance.py:1244} INFO - Starting attempt 1 of 3
[2022-03-17 19:01:28,848] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-17 19:01:28,867] {taskinstance.py:1264} INFO - Executing <Task(StageToRedshiftOperator): task_loadDataFromS3ToTrips.Stage_staging_songs> on 2022-03-17 10:00:00+00:00
[2022-03-17 19:01:28,870] {standard_task_runner.py:52} INFO - Started process 42709 to run task
[2022-03-17 19:01:28,879] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'udac_example_dag', 'task_loadDataFromS3ToTrips.Stage_staging_songs', 'scheduled__2022-03-17T10:00:00+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/var/folders/lh/ngst1lt51m9_gyz7qrg2f3nh0000gn/T/tmpbq81jwoc', '--error-file', '/var/folders/lh/ngst1lt51m9_gyz7qrg2f3nh0000gn/T/tmpgj3pm89g']
[2022-03-17 19:01:28,881] {standard_task_runner.py:77} INFO - Job 170: Subtask task_loadDataFromS3ToTrips.Stage_staging_songs
[2022-03-17 19:01:28,980] {logging_mixin.py:109} INFO - Running <TaskInstance: udac_example_dag.task_loadDataFromS3ToTrips.Stage_staging_songs scheduled__2022-03-17T10:00:00+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2022-03-17 19:01:29,053] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=udac_example_dag
AIRFLOW_CTX_TASK_ID=task_loadDataFromS3ToTrips.Stage_staging_songs
AIRFLOW_CTX_EXECUTION_DATE=2022-03-17T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-17T10:00:00+00:00
[2022-03-17 19:01:29,054] {stage_redshift.py:75} INFO - Starting to set aws redshift connection
[2022-03-17 19:01:29,065] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-17 19:01:29,079] {stage_redshift.py:79} INFO - Starting to truncate table, table name: staging_songs!
[2022-03-17 19:01:29,079] {stage_redshift.py:144} INFO - Starting to execute the truncate_table_sql process
[2022-03-17 19:01:29,089] {base.py:70} INFO - Using connection to: id: redshift. Host: redshift-cluster-1.cvmsgkpkbsh2.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: ***, extra: {}
[2022-03-17 19:01:30,425] {dbapi.py:225} INFO - Running statement: 
        TRUNCATE TABLE public.staging_songs
        , parameters: None
[2022-03-17 19:01:31,046] {stage_redshift.py:83} INFO - Starting to copy data from S3 to Redshift table, table name: staging_songs!
[2022-03-17 19:01:31,050] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-03-17 19:01:31,051] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2022-03-17 19:01:31,052] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2022-03-17 19:01:31,053] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2022-03-17 19:01:31,054] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2022-03-17 19:01:31,054] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-03-17 19:01:31,055] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2022-03-17 19:01:31,056] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2022-03-17 19:01:31,057] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2022-03-17 19:01:31,058] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-03-17 19:01:31,058] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2022-03-17 19:01:31,059] {logging_mixin.py:109} WARNING - /usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-03-17 19:01:31,060] {stage_redshift.py:121} INFO - S3_key.format(**context): song_data
[2022-03-17 19:01:31,060] {stage_redshift.py:125} INFO - Starting to execute the copy_sql_statement process
[2022-03-17 19:01:31,068] {base.py:70} INFO - Using connection to: id: redshift. Host: redshift-cluster-1.cvmsgkpkbsh2.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: ***, extra: {}
[2022-03-17 19:01:32,335] {dbapi.py:225} INFO - Running statement: 
        COPY staging_songs
        FROM 's3://udacity-dend/song_data'
        ACCESS_KEY_ID 'AKIAUW7BQYXKOEMAW7ES'
        SECRET_ACCESS_KEY '***'
        FORMAT AS JSON 'auto'
        REGION AS 'us-west-2'
        , parameters: None
[2022-03-17 19:03:39,419] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/Users/oneforall_nick/workspace/airflow/plugins/operators/stage_redshift.py", line 84, in execute
    self.copy_data(access_key, secret_key, redshift_hook, context)
  File "/Users/oneforall_nick/workspace/airflow/plugins/operators/stage_redshift.py", line 135, in copy_data
    redshift_hook.run(copy_sql_statement)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.OperationalError: SSL SYSCALL error: EOF detected

[2022-03-17 19:03:39,437] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=udac_example_dag, task_id=task_loadDataFromS3ToTrips.Stage_staging_songs, execution_date=20220317T100000, start_date=20220317T110128, end_date=20220317T110339
[2022-03-17 19:03:39,458] {standard_task_runner.py:89} ERROR - Failed to execute job 170 for task task_loadDataFromS3ToTrips.Stage_staging_songs
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/Users/oneforall_nick/workspace/airflow/plugins/operators/stage_redshift.py", line 84, in execute
    self.copy_data(access_key, secret_key, redshift_hook, context)
  File "/Users/oneforall_nick/workspace/airflow/plugins/operators/stage_redshift.py", line 135, in copy_data
    redshift_hook.run(copy_sql_statement)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/anaconda3/envs/data_pipeline/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.OperationalError: SSL SYSCALL error: EOF detected

[2022-03-17 19:03:39,496] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-17 19:03:39,538] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
